server:
  port: 8080

spring:
  application:
    name: intershop
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: postgres
    password: admin
  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: 127.0.0.1
      port: 6379
  sql:
    init:
      mode: always
  thymeleaf:
    encoding: UTF-8
    cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---
spring:
  config:
    activate:
      on-profile: ci,test
  r2dbc:
    url: r2dbc:h2:mem:///~/db/intershop
    username: test
    password:
  data:
    r2dbc:
      repositories:
        enabled: true
  h2:
    console:
      enabled: true