CREATE TABLE IF NOT EXISTS wares (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)  NOT NULL,
    description VARCHAR(1000),
    image       BYTEA,
    price       DECIMAL,
    created_at  TIMESTAMP DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat        VARCHAR(32) NOT NULL,
    created_at  TIMESTAMP DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL,
    ware_id     BIGINT NOT NULL,
    count       SMALLINT DEFAULT 1,
    created_at  TIMESTAMP DEFAULT (now()),
    CONSTRAINT fk_items_ref_order FOREIGN KEY(order_id) REFERENCES orders(id),
    CONSTRAINT fk_items_ref_ware FOREIGN KEY(ware_id) REFERENCES wares(id)
);
